[application]
name = "AnA"
default_platform = "web"
out_dir = "dist"
asset_dir = "public"

[web.app]
title = "AnA"

[web.watcher]
reload_html = true
index_on_404 = true
watch_path = ["src", "public"]

[web.resource]
style = ["./public/style.css"]
script = []

[[web.proxy]]
backend = "http://localhost:8000/api/"

[web.resource.dev]